### ISSUE TITLE
如何使用与修改

### ISSUE THREAD

**Issue by keyescgm** [raoweijian/jacoco-diff#2]
有俩张关键图片看不了，裂开了···
要修改python的代码如何?

**Comment by raoweijian** [comment]
稍等哈，我下班后更新一下文档

**Comment by keyescgm** [comment]
好的，大佬~~~啥时候下班，找了很多资料都是不全的，你这个工具应该是最接近我要的结果，但是一运行python就各种报错，我估计还是没理解python脚本的功能与作用，感谢大佬指点····


 


------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 下午4:11
收件人: "raoweijian/jacoco-diff"<jacoco-diff@noreply.github.com>;
抄送: "第一号伤心人"<1175426782@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [raoweijian/jacoco-diff] 如何使用与修改 (#2)




稍等哈，我下班后更新一下文档

**Comment by raoweijian** [comment]
你好，我看了一下你邮件里的截图，你应该是对python的包管理不太熟悉。这个脚本工具用到了一些非官方的库，需要安装的。你是windows 客户端的话，可以执行 pip install gitpython 来安装 git 库。

另外，看你目录的截图，不像是通过maven跑出来的覆盖率数据，似乎目录结构有些不对。在使用这个工具的时候，可能需要做一些调整。具体的我这里也没拿到你的工程目录，不太好调试。你可能需要学习一点 python 的相关语法自己改一下脚本了。

**Comment by keyescgm** [comment]
我是gradle构建的，Android项目




发自我的iPhone

------------------ 原始邮件 ------------------
发件人: Weijian Rao <notifications@github.com>
发送时间: 2019年6月13日 19:14
收件人: raoweijian/jacoco-diff <jacoco-diff@noreply.github.com>
抄送: 第一号伤心人 <1175426782@qq.com>, Author <author@noreply.github.com>
主题: 回复：[raoweijian/jacoco-diff] 如何使用与修改 (#2)




你好，我看了一下你邮件里的截图，你应该是对python的包管理不太熟悉。这个脚本工具用到了一些非官方的库，需要安装的。你是windows 客户端的话，可以执行 pip install gitpython 来安装 git 库。
 
另外，看你目录的截图，不像是通过maven跑出来的覆盖率数据，似乎目录结构有些不对。在使用这个工具的时候，可能需要做一些调整。具体的我这里也没拿到你的工程目录，不太好调试。你可能需要学习一点 python 的相关语法自己改一下脚本了。

**Comment by keyescgm** [comment]
hello，大佬！
如果没有子模块咋修改？
最后能生成与jacoco一样的增量的结果




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 晚上7:14
收件人: "raoweijian/jacoco-diff"<jacoco-diff@noreply.github.com>;
抄送: "第一号伤心人"<1175426782@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [raoweijian/jacoco-diff] 如何使用与修改 (#2)




你好，我看了一下你邮件里的截图，你应该是对python的包管理不太熟悉。这个脚本工具用到了一些非官方的库，需要安装的。你是windows 客户端的话，可以执行 pip install gitpython 来安装 git 库。
 
另外，看你目录的截图，不像是通过maven跑出来的覆盖率数据，似乎目录结构有些不对。在使用这个工具的时候，可能需要做一些调整。具体的我这里也没拿到你的工程目录，不太好调试。你可能需要学习一点 python 的相关语法自己改一下脚本了。

**Comment by keyescgm** [comment]
Hi，大佬~~现在可以把脚本通，但是覆盖率都是0，实际上确实有覆盖···




------------------ 原始邮件 ------------------
发件人: "notifications"<notifications@github.com>;
发送时间: 2019年6月13日(星期四) 晚上7:14
收件人: "raoweijian/jacoco-diff"<jacoco-diff@noreply.github.com>;
抄送: "第一号伤心人"<1175426782@qq.com>;"Author"<author@noreply.github.com>;
主题: Re: [raoweijian/jacoco-diff] 如何使用与修改 (#2)




你好，我看了一下你邮件里的截图，你应该是对python的包管理不太熟悉。这个脚本工具用到了一些非官方的库，需要安装的。你是windows 客户端的话，可以执行 pip install gitpython 来安装 git 库。
 
另外，看你目录的截图，不像是通过maven跑出来的覆盖率数据，似乎目录结构有些不对。在使用这个工具的时候，可能需要做一些调整。具体的我这里也没拿到你的工程目录，不太好调试。你可能需要学习一点 python 的相关语法自己改一下脚本了。

**Comment by 512433465** [comment]
图挂了，可否补个图。
我这边用java生成了增量报告。但是增量报告是基于方法分支覆盖的。
我这边只想生成变更行覆盖率报告。所以想参考一下你的项目

**Comment by SankiaW** [comment]
请问针对在线插桩的测试覆盖率似乎不兼容

**Comment by raoweijian** [comment]
> 请问针对在线插桩的测试覆盖率似乎不兼容

在线查桩，只要有源码和对应的 jacoco 报告，都是可以支持的嘛。
这个项目只是一个离线运行的工具，可以在任何需要的时候执行。

**Comment by raoweijian** [comment]
> 图挂了，可否补个图。
> 我这边用java生成了增量报告。但是增量报告是基于方法分支覆盖的。
> 我这边只想生成变更行覆盖率报告。所以想参考一下你的项目
你好，图已经补上了。另外，我这边生成的也是行覆盖率呀，没有分支覆盖率的信息。
